export const initialClones = [
  {
    cloneid: "10001",
    name: "Jimmy Dendrinos",
    imageUrl: "/images/clones/jimmy-clone.png",
    traits: ["Music Festival Photographer", "Developer + Creator"],
    username: "jimmygpt",
  },
  {
    cloneid: "10002",
    name: "Sarah Smith",
    imageUrl: "/images/clones/sarah-clone.png",
    traits: ["Real Estate Attorney", "Amateur Investor"],
    username: "ssmith",
  },
  {
    cloneid: "10003",
    name: "David Myers",
    imageUrl: "/images/clones/david-clone.png",
    traits: ["Financial Advisor", "Visited All 50 States"],
    username: "myersfinancial",
  },
  {
    cloneid: "10004",
    name: "Emily Chen",
    imageUrl: "/images/clones/emily-clone.png",
    traits: ["Data Scientist", "Competitive Rock Climber"],
    username: "emilyc_datarocks",
  },
  {
    cloneid: "10005",
    name: "Marcus Johnson",
    imageUrl: "/images/clones/marcus-clone.png",
    traits: ["Michelin-Star Chef", "Food Blogger"],
    username: "chef_marcus",
  },
  {
    cloneid: "10006",
    name: "Olivia Patel",
    imageUrl: "/images/clones/olivia-clone.png",
    traits: ["Environmental Lawyer", "Yoga Instructor"],
    username: "olivia_greenpeace",
  },
  {
    cloneid: "10007",
    name: "Claudia Rodriguez",
    imageUrl: "/images/clones/claudia-clone.png",
    traits: ["Aerospace Engineer", "Amateur Astronomer"],
    username: "space_alex",
  },
  {
    cloneid: "10008",
    name: "Sophia Lee",
    imageUrl: "/images/clones/sophia-clone.png",
    traits: ["Neuroscientist", "Classical Pianist"],
    username: "brainmusic_sophia",
  },
  {
    cloneid: "10009",
    name: "Jack Brown",
    imageUrl: "/images/clones/jack-clone.png",
    traits: ["Wildlife Conservationist", "Nature Photographer"],
    username: "wild_jackson",
  },
];

export const secondaryClones = [
  {
    cloneid: "10010",
    name: "Linda Collins",
    imageUrl: "/images/clones/linda-clone.png",
    traits: ["Author", "English Professor"],
    username: "professor_collins",
  },
  {
    cloneid: "10011",
    name: "Ethan Nguyen",
    imageUrl: "/images/clones/ethan-clone.png",
    traits: ["Salesman", "Marathon Runner"],
    username: "letsrun",
  },
  {
    cloneid: "10012",
    name: "Zoe Garcia",
    imageUrl: "/images/clones/zoe-clone.png",
    traits: ["Marine Biologist", "Scuba Diving Instructor"],
    username: "zoe_ocean_explorer",
  },
  {
    cloneid: "10013",
    name: "Liam O'Keeffe",
    imageUrl: "/images/clones/liam-clone.png",
    traits: ["Model", "Amateur Meteorologist"],
    username: "liam",
  },
  {
    cloneid: "10014",
    name: "Sasha Khan",
    imageUrl: "/images/clones/sasha-clone.png",
    traits: ["Painter", "Salsa Dancer"],
    username: "sasha_k",
  },
  {
    cloneid: "10015",
    name: "Mike Saunters",
    imageUrl: "/images/clones/mike-clone.png",
    traits: ["Urban Planner", "Street Artist"],
    username: "firstCityMike",
  },
  {
    cloneid: "10016",
    name: "Emma Clarke",
    imageUrl: "/images/clones/emma-clone.png",
    traits: ["Family Doctor", "Loves to Travel"],
    username: "emma_travels",
  },
  {
    cloneid: "10017",
    name: "Amit Desai",
    imageUrl: "/images/clones/amit-clone.png",
    traits: ["Pediatric Surgeon", "Cricket Fanatic"],
    username: "cricketfanatic",
  },
  {
    cloneid: "10018",
    name: "Brit Tanaka",
    imageUrl: "/images/clones/brit-clone.png",
    traits: ["Tattoo Artist", "Tea Ceremony Master"],
    username: "bluebrit",
  },
];
